import json

# Read original notebook
with open('forex_lstm_study.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Remove any previously added feature engineering cells (cells beyond the original 6)
nb['cells'] = nb['cells'][:6]

# Step 2 markdown
step2_md = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "## Step 2: Feature Engineering\n",
        "\n",
        "Implementing all technical and statistical indicators from Table 3 and Section 3.3 of the study.\n",
        "\n",
        "### Technical Indicators:\n",
        "- **Momentum**: EMA, MACD, ADX\n",
        "- **Oscillators**: RSI, Stochastic, CCI, Williams %R\n",
        "- **Volatility**: Bollinger Bands, ATR\n",
        "\n",
        "### Statistical Indicators:\n",
        "- Momentum, Average Price, Range, OHLC"
    ]
}

# Main feature engineering code cell
features_main = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Create a copy for feature engineering\n",
        "df_features = df.copy()\n",
        "\n",
        "print(\"Starting feature engineering...\")\n",
        "print(f\"Initial shape: {df_features.shape}\")\n",
        "\n",
        "# ============================================================================\n",
        "# 3.3.4 STATISTICAL INDICATORS (Calculate first as they're simple)\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n[1/4] Calculating Statistical Indicators...\")\n",
        "\n",
        "# Momentum = Open_t - Close_t (Equation 27)\n",
        "df_features['momentum'] = df_features['open'] - df_features['close']\n",
        "\n",
        "# Average Price = (Low_t + High_t) / 2 (Equation 28)\n",
        "df_features['avg_price'] = (df_features['low'] + df_features['high']) / 2\n",
        "\n",
        "# Range = High_t - Low_t (Equation 29)\n",
        "df_features['range'] = df_features['high'] - df_features['low']\n",
        "\n",
        "# OHLC = (Open_t + Close_t + Low_t + High_t) / 4 (Equation 30)\n",
        "df_features['ohlc'] = (df_features['open'] + df_features['close'] + \n",
        "                        df_features['low'] + df_features['high']) / 4\n",
        "\n",
        "print(\"   - Momentum, Average Price, Range, OHLC: Done\")\n",
        "\n",
        "# ============================================================================\n",
        "# 3.3.1 MOMENTUM INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n[2/4] Calculating Momentum Indicators...\")\n",
        "\n",
        "# Exponential Moving Averages (EMA) - Settings: 10, 20, 50, 100, 200\n",
        "for period in [10, 20, 50, 100, 200]:\n",
        "    df_features[f'ema_{period}'] = df_features['close'].ewm(span=period, adjust=False).mean()\n",
        "    \n",
        "print(\"   - EMA (10, 20, 50, 100, 200): Done\")\n",
        "\n",
        "# Moving Average Convergence Divergence (MACD) - Settings: 26, 12, 9\n",
        "ema_fast = df_features['close'].ewm(span=12, adjust=False).mean()\n",
        "ema_slow = df_features['close'].ewm(span=26, adjust=False).mean()\n",
        "df_features['macd'] = ema_fast - ema_slow  # MACD line (Equation 5)\n",
        "df_features['macd_signal'] = df_features['macd'].ewm(span=9, adjust=False).mean()  # Signal line (Equation 6)\n",
        "df_features['macd_hist'] = df_features['macd'] - df_features['macd_signal']  # Histogram\n",
        "\n",
        "print(\"   - MACD (26, 12, 9): Done\")\n",
        "\n",
        "# Average Directional Index (ADX) - Setting: 14\n",
        "# Calculate +DM and -DM\n",
        "high_diff = df_features['high'].diff()\n",
        "low_diff = -df_features['low'].diff()\n",
        "\n",
        "plus_dm = high_diff.copy()\n",
        "plus_dm[high_diff < low_diff] = 0\n",
        "plus_dm[plus_dm < 0] = 0\n",
        "\n",
        "minus_dm = low_diff.copy()\n",
        "minus_dm[low_diff < high_diff] = 0\n",
        "minus_dm[minus_dm < 0] = 0\n",
        "\n",
        "# Calculate ATR for ADX (needed for normalization)\n",
        "tr1 = df_features['high'] - df_features['low']\n",
        "tr2 = abs(df_features['high'] - df_features['close'].shift(1))\n",
        "tr3 = abs(df_features['low'] - df_features['close'].shift(1))\n",
        "tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)\n",
        "atr_14 = tr.rolling(window=14).mean()\n",
        "\n",
        "# Smooth +DM and -DM\n",
        "plus_dm_smooth = plus_dm.rolling(window=14).mean()\n",
        "minus_dm_smooth = minus_dm.rolling(window=14).mean()\n",
        "\n",
        "# Calculate +DI and -DI (Equations 7, 8)\n",
        "plus_di = 100 * (plus_dm_smooth / atr_14)\n",
        "minus_di = 100 * (minus_dm_smooth / atr_14)\n",
        "\n",
        "# Calculate DX (Equation 9)\n",
        "dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di)\n",
        "\n",
        "# Calculate ADX (Equation 10)\n",
        "df_features['adx'] = dx.rolling(window=14).mean()\n",
        "df_features['plus_di'] = plus_di\n",
        "df_features['minus_di'] = minus_di\n",
        "\n",
        "print(\"   - ADX (14): Done\")\n",
        "\n",
        "# ============================================================================\n",
        "# 3.3.2 OSCILLATOR INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n[3/4] Calculating Oscillator Indicators...\")\n",
        "\n",
        "# Relative Strength Index (RSI) - Setting: 14\n",
        "delta = df_features['close'].diff()\n",
        "gain = delta.copy()\n",
        "loss = delta.copy()\n",
        "gain[gain < 0] = 0\n",
        "loss[loss > 0] = 0\n",
        "loss = abs(loss)\n",
        "\n",
        "avg_gain = gain.rolling(window=14).mean()\n",
        "avg_loss = loss.rolling(window=14).mean()\n",
        "\n",
        "rs = avg_gain / avg_loss\n",
        "df_features['rsi'] = 100 - (100 / (1 + rs))  # Equation 14\n",
        "\n",
        "print(\"   - RSI (14): Done\")\n",
        "\n",
        "# Stochastic Oscillator - Settings: 14, 3\n",
        "low_14 = df_features['low'].rolling(window=14).min()\n",
        "high_14 = df_features['high'].rolling(window=14).max()\n",
        "\n",
        "df_features['stoch_k'] = 100 * ((df_features['close'] - low_14) / (high_14 - low_14))  # Equation 15\n",
        "df_features['stoch_d'] = df_features['stoch_k'].rolling(window=3).mean()  # Equation 16\n",
        "\n",
        "print(\"   - Stochastic Oscillator (14, 3): Done\")\n",
        "\n",
        "# Commodity Channel Index (CCI) - Settings: 20, 0.015\n",
        "tp = (df_features['high'] + df_features['low'] + df_features['close']) / 3  # Typical Price (Equation 17)\n",
        "ma_tp = tp.rolling(window=20).mean()  # Moving Average (Equation 18)\n",
        "md = abs(tp - ma_tp).rolling(window=20).mean()  # Mean Deviation (Equation 19)\n",
        "df_features['cci'] = (tp - ma_tp) / (0.015 * md)  # Equation 20\n",
        "\n",
        "print(\"   - CCI (20, 0.015): Done\")\n",
        "\n",
        "# Williams %R - Setting: 14\n",
        "high_14 = df_features['high'].rolling(window=14).max()\n",
        "low_14 = df_features['low'].rolling(window=14).min()\n",
        "df_features['williams_r'] = -100 * ((high_14 - df_features['close']) / (high_14 - low_14))  # Equation 21\n",
        "\n",
        "print(\"   - Williams %R (14): Done\")\n",
        "\n",
        "# ============================================================================\n",
        "# 3.3.3 VOLATILITY INDICATORS\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n[4/4] Calculating Volatility Indicators...\")\n",
        "\n",
        "# Bollinger Bands - Settings: 20, 2\n",
        "sma_20 = df_features['close'].rolling(window=20).mean()\n",
        "std_20 = df_features['close'].rolling(window=20).std()\n",
        "\n",
        "df_features['bb_middle'] = sma_20  # Equation 22\n",
        "df_features['bb_upper'] = sma_20 + (2 * std_20)  # Equation 23\n",
        "df_features['bb_lower'] = sma_20 - (2 * std_20)  # Equation 24\n",
        "df_features['bb_width'] = df_features['bb_upper'] - df_features['bb_lower']\n",
        "df_features['bb_position'] = (df_features['close'] - df_features['bb_lower']) / df_features['bb_width']\n",
        "\n",
        "print(\"   - Bollinger Bands (20, 2): Done\")\n",
        "\n",
        "# Average True Range (ATR) - Setting: 14\n",
        "df_features['atr'] = atr_14  # Equation 26\n",
        "\n",
        "print(\"   - ATR (14): Done\")\n",
        "\n",
        "# ============================================================================\n",
        "# SUMMARY\n",
        "# ============================================================================\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"Feature Engineering Complete!\")\n",
        "print(\"=\"*60)\n",
        "print(f\"\\nFinal shape: {df_features.shape}\")\n",
        "print(f\"Total features created: {df_features.shape[1] - df.shape[1]}\")\n",
        "print(f\"\\nFeature categories:\")\n",
        "print(f\"  - Original columns: {df.shape[1]}\")\n",
        "print(f\"  - Statistical indicators: 4\")\n",
        "print(f\"  - EMAs: 5\")\n",
        "print(f\"  - MACD: 3\")\n",
        "print(f\"  - ADX: 3\")\n",
        "print(f\"  - RSI: 1\")\n",
        "print(f\"  - Stochastic: 2\")\n",
        "print(f\"  - CCI: 1\")\n",
        "print(f\"  - Williams %R: 1\")\n",
        "print(f\"  - Bollinger Bands: 5\")\n",
        "print(f\"  - ATR: 1\")\n",
        "\n",
        "# Display first few rows with new features\n",
        "print(\"\\nSample of features (first 5 rows, last 10 columns):\")\n",
        "print(df_features.iloc[:5, -10:])"
    ]
}

# Missing values check cell
missing_check = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Check for missing values\n",
        "print(\"Missing values per feature:\")\n",
        "missing = df_features.isnull().sum()\n",
        "print(missing[missing > 0].sort_values(ascending=False))\n",
        "\n",
        "print(f\"\\nTotal rows with any missing values: {df_features.isnull().any(axis=1).sum()}\")\n",
        "print(f\"Percentage of rows with missing values: {df_features.isnull().any(axis=1).sum() / len(df_features) * 100:.2f}%\")"
    ]
}

# Visualization cell
viz_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Visualize some key technical indicators\n",
        "fig, axes = plt.subplots(4, 1, figsize=(14, 12))\n",
        "\n",
        "# Plot 1: Price with EMAs\n",
        "ax1 = axes[0]\n",
        "ax1.plot(df_features.index[-252:], df_features['close'].iloc[-252:], label='Close Price', linewidth=2)\n",
        "ax1.plot(df_features.index[-252:], df_features['ema_10'].iloc[-252:], label='EMA 10', alpha=0.7)\n",
        "ax1.plot(df_features.index[-252:], df_features['ema_50'].iloc[-252:], label='EMA 50', alpha=0.7)\n",
        "ax1.plot(df_features.index[-252:], df_features['ema_200'].iloc[-252:], label='EMA 200', alpha=0.7)\n",
        "ax1.set_title('Price with Exponential Moving Averages (Last Year)', fontweight='bold')\n",
        "ax1.set_ylabel('Price')\n",
        "ax1.legend(loc='best')\n",
        "ax1.grid(True, alpha=0.3)\n",
        "\n",
        "# Plot 2: RSI\n",
        "ax2 = axes[1]\n",
        "ax2.plot(df_features.index[-252:], df_features['rsi'].iloc[-252:], label='RSI', color='purple')\n",
        "ax2.axhline(y=70, color='r', linestyle='--', alpha=0.5, label='Overbought (70)')\n",
        "ax2.axhline(y=30, color='g', linestyle='--', alpha=0.5, label='Oversold (30)')\n",
        "ax2.set_title('Relative Strength Index (RSI)', fontweight='bold')\n",
        "ax2.set_ylabel('RSI')\n",
        "ax2.set_ylim(0, 100)\n",
        "ax2.legend(loc='best')\n",
        "ax2.grid(True, alpha=0.3)\n",
        "\n",
        "# Plot 3: MACD\n",
        "ax3 = axes[2]\n",
        "ax3.plot(df_features.index[-252:], df_features['macd'].iloc[-252:], label='MACD', color='blue')\n",
        "ax3.plot(df_features.index[-252:], df_features['macd_signal'].iloc[-252:], label='Signal', color='red')\n",
        "ax3.bar(df_features.index[-252:], df_features['macd_hist'].iloc[-252:], label='Histogram', alpha=0.3, color='gray')\n",
        "ax3.set_title('MACD (Moving Average Convergence Divergence)', fontweight='bold')\n",
        "ax3.set_ylabel('MACD')\n",
        "ax3.legend(loc='best')\n",
        "ax3.grid(True, alpha=0.3)\n",
        "\n",
        "# Plot 4: Bollinger Bands\n",
        "ax4 = axes[3]\n",
        "ax4.plot(df_features.index[-252:], df_features['close'].iloc[-252:], label='Close Price', linewidth=2, color='black')\n",
        "ax4.plot(df_features.index[-252:], df_features['bb_upper'].iloc[-252:], label='Upper Band', linestyle='--', color='red', alpha=0.7)\n",
        "ax4.plot(df_features.index[-252:], df_features['bb_middle'].iloc[-252:], label='Middle Band', linestyle='--', color='blue', alpha=0.7)\n",
        "ax4.plot(df_features.index[-252:], df_features['bb_lower'].iloc[-252:], label='Lower Band', linestyle='--', color='green', alpha=0.7)\n",
        "ax4.fill_between(df_features.index[-252:], df_features['bb_lower'].iloc[-252:], df_features['bb_upper'].iloc[-252:], alpha=0.1)\n",
        "ax4.set_title('Bollinger Bands', fontweight='bold')\n",
        "ax4.set_ylabel('Price')\n",
        "ax4.set_xlabel('Date')\n",
        "ax4.legend(loc='best')\n",
        "ax4.grid(True, alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print(\"Technical indicators visualization complete!\")"
    ]
}

# Save cell
save_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Save the features dataframe for later use\n",
        "df_features.to_csv('data/EURUSD_1day_with_features.csv')\n",
        "print(\"Features saved to 'data/EURUSD_1day_with_features.csv'\")\n",
        "\n",
        "# Display summary statistics for all features\n",
        "print(\"\\nSummary statistics for technical indicators:\")\n",
        "feature_cols = [col for col in df_features.columns if col not in df.columns]\n",
        "print(df_features[feature_cols].describe().T)"
    ]
}

# Add all cells
nb['cells'].extend([step2_md, features_main, missing_check, viz_cell, save_cell])

# Save with ORIGINAL metadata preserved
with open('forex_lstm_study.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Feature engineering cells added!")
print(f"Kernel preserved: {nb['metadata']['kernelspec']['display_name']}")
print(f"Total cells: {len(nb['cells'])}")
print("Ready to run in Jupyter!")
