"""
Forex Backtesting Engine
Provides a robust framework for testing trading strategies with proper risk management
"""
import pandas as pd
import numpy as np
from typing import Dict, List, Tuple
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Position:
    """Represents an open trading position"""
    entry_time: datetime
    entry_price: float
    size: float
    direction: str  # 'long' or 'short'
    stop_loss: float = None
    take_profit: float = None


@dataclass
class Trade:
    """Represents a completed trade"""
    entry_time: datetime
    exit_time: datetime
    entry_price: float
    exit_price: float
    size: float
    direction: str
    pnl: float
    pnl_pct: float
    return_pct: float


@dataclass
class BacktestResult:
    """Contains backtest results and metrics"""
    trades: List[Trade] = field(default_factory=list)
    equity_curve: pd.DataFrame = None
    metrics: Dict = field(default_factory=dict)


class Backtester:
    """Backtesting engine for forex strategies"""

    def __init__(self, initial_capital=10000, risk_per_trade=0.02, commission=0.0):
        """
        Initialize backtester

        Args:
            initial_capital: Starting capital
            risk_per_trade: Risk per trade as fraction of capital (default 2%)
            commission: Commission per trade as fraction (e.g., 0.0001 for 1 pip)
        """
        self.initial_capital = initial_capital
        self.risk_per_trade = risk_per_trade
        self.commission = commission
        self.reset()

    def reset(self):
        """Reset backtester state"""
        self.capital = self.initial_capital
        self.position = None
        self.trades = []
        self.equity_history = []

    def run(self, data: pd.DataFrame, strategy) -> BacktestResult:
        """
        Run backtest on data using strategy

        Args:
            data: DataFrame with OHLCV data
            strategy: Strategy instance with generate_signals method

        Returns:
            BacktestResult with trades and metrics
        """
        self.reset()

        # Generate signals from strategy
        signals = strategy.generate_signals(data.copy())

        if signals is None or signals.empty:
            print("No signals generated by strategy")
            return BacktestResult()

        # Ensure we have required columns
        required_cols = ['date', 'open', 'high', 'low', 'close']
        if not all(col in signals.columns for col in required_cols):
            print(f"Missing required columns. Has: {signals.columns.tolist()}")
            return BacktestResult()

        # Run backtest
        for i in range(len(signals)):
            row = signals.iloc[i]

            # Record equity
            self.equity_history.append({
                'date': row['date'],
                'equity': self.capital,
                'position': 'long' if self.position and self.position.direction == 'long'
                           else ('short' if self.position else 'flat')
            })

            # Check for exit signals first
            if self.position:
                self._check_exit(row)

            # Check for entry signals
            if not self.position:
                self._check_entry(row, signals, i)

        # Close any open position at end
        if self.position:
            last_row = signals.iloc[-1]
            self._close_position(last_row['date'], last_row['close'], 'end_of_data')

        # Create result
        result = BacktestResult()
        result.trades = self.trades
        result.equity_curve = pd.DataFrame(self.equity_history)
        result.metrics = self._calculate_metrics()

        return result

    def _check_entry(self, row, signals, idx):
        """Check for entry signals"""
        if 'signal' not in signals.columns:
            return

        signal = row['signal']

        if signal == 1:  # Long signal
            self._enter_position(row, 'long')
        elif signal == -1:  # Short signal
            self._enter_position(row, 'short')

    def _enter_position(self, row, direction):
        """Enter a new position"""
        price = row['close']

        # Calculate position size based on risk
        # For simplicity, using fixed risk per trade
        if 'stop_loss' in row and pd.notna(row['stop_loss']):
            stop_distance = abs(price - row['stop_loss'])
            if stop_distance > 0:
                risk_amount = self.capital * self.risk_per_trade
                size = risk_amount / stop_distance
            else:
                size = self.capital * self.risk_per_trade / price
        else:
            # If no stop loss, use 2% of capital
            size = (self.capital * self.risk_per_trade) / price

        self.position = Position(
            entry_time=row['date'],
            entry_price=price,
            size=size,
            direction=direction,
            stop_loss=row.get('stop_loss'),
            take_profit=row.get('take_profit')
        )

    def _check_exit(self, row):
        """Check if position should be exited"""
        if not self.position:
            return

        exit_signal = False
        exit_price = None
        exit_reason = None

        # Check stop loss
        if self.position.stop_loss:
            if self.position.direction == 'long' and row['low'] <= self.position.stop_loss:
                exit_signal = True
                exit_price = self.position.stop_loss
                exit_reason = 'stop_loss'
            elif self.position.direction == 'short' and row['high'] >= self.position.stop_loss:
                exit_signal = True
                exit_price = self.position.stop_loss
                exit_reason = 'stop_loss'

        # Check take profit
        if not exit_signal and self.position.take_profit:
            if self.position.direction == 'long' and row['high'] >= self.position.take_profit:
                exit_signal = True
                exit_price = self.position.take_profit
                exit_reason = 'take_profit'
            elif self.position.direction == 'short' and row['low'] <= self.position.take_profit:
                exit_signal = True
                exit_price = self.position.take_profit
                exit_reason = 'take_profit'

        # Check for signal-based exit
        if not exit_signal and 'signal' in row and row['signal'] == 0:
            exit_signal = True
            exit_price = row['close']
            exit_reason = 'signal'

        if exit_signal:
            self._close_position(row['date'], exit_price, exit_reason)

    def _close_position(self, exit_time, exit_price, reason):
        """Close current position"""
        if not self.position:
            return

        # Calculate P&L
        if self.position.direction == 'long':
            pnl_pct = (exit_price - self.position.entry_price) / self.position.entry_price
        else:  # short
            pnl_pct = (self.position.entry_price - exit_price) / self.position.entry_price

        # Apply commission
        pnl_pct -= 2 * self.commission  # Entry and exit

        pnl = self.position.size * self.position.entry_price * pnl_pct

        # Update capital
        self.capital += pnl

        # Record trade
        trade = Trade(
            entry_time=self.position.entry_time,
            exit_time=exit_time,
            entry_price=self.position.entry_price,
            exit_price=exit_price,
            size=self.position.size,
            direction=self.position.direction,
            pnl=pnl,
            pnl_pct=pnl_pct,
            return_pct=pnl / self.capital * 100
        )
        self.trades.append(trade)

        # Clear position
        self.position = None

    def _calculate_metrics(self) -> Dict:
        """Calculate performance metrics"""
        if not self.trades:
            return {
                'total_trades': 0,
                'total_return_pct': 0,
                'total_return': 0
            }

        df_trades = pd.DataFrame([vars(t) for t in self.trades])

        # Basic metrics
        total_trades = len(self.trades)
        winning_trades = df_trades[df_trades['pnl'] > 0]
        losing_trades = df_trades[df_trades['pnl'] < 0]

        win_rate = len(winning_trades) / total_trades * 100 if total_trades > 0 else 0

        avg_win = winning_trades['pnl'].mean() if len(winning_trades) > 0 else 0
        avg_loss = losing_trades['pnl'].mean() if len(losing_trades) > 0 else 0

        profit_factor = (abs(winning_trades['pnl'].sum()) / abs(losing_trades['pnl'].sum())
                        if len(losing_trades) > 0 and losing_trades['pnl'].sum() != 0 else 0)

        total_return = self.capital - self.initial_capital
        total_return_pct = (self.capital / self.initial_capital - 1) * 100

        # Calculate max drawdown
        equity_curve = pd.DataFrame(self.equity_history)
        if not equity_curve.empty:
            equity_curve['cummax'] = equity_curve['equity'].cummax()
            equity_curve['drawdown'] = (equity_curve['equity'] - equity_curve['cummax']) / equity_curve['cummax'] * 100
            max_drawdown = equity_curve['drawdown'].min()
        else:
            max_drawdown = 0

        # Sharpe ratio (simplified, assuming daily data)
        if len(df_trades) > 1:
            returns = df_trades['pnl_pct'].values
            sharpe = np.mean(returns) / np.std(returns) * np.sqrt(252) if np.std(returns) > 0 else 0
        else:
            sharpe = 0

        return {
            'total_trades': total_trades,
            'winning_trades': len(winning_trades),
            'losing_trades': len(losing_trades),
            'win_rate': win_rate,
            'avg_win': avg_win,
            'avg_loss': avg_loss,
            'profit_factor': profit_factor,
            'total_return': total_return,
            'total_return_pct': total_return_pct,
            'max_drawdown': max_drawdown,
            'sharpe_ratio': sharpe,
            'final_capital': self.capital
        }
